version: '3.4'

networks:
    backend:

services:
    peakplannerdb: 
        container_name: peakplanner
        image: mysql:8.0.33-oracle
        environment: 
            - MYSQL_ROOT_PASSWORD=12345678
        ports:
            - 8003:3306
        networks:
            - backend
    peakplannerapi:
        container_name: peak-planner-api
        image: ${DOCKER_REGISTRY-}peakplannerapi
        build:
            context: .
            dockerfile: PeakPlanner/Dockerfile
        networks:
            - backend
        ports:
            - 8004:80
        environment:
            - DB_HOST=peakplannerdb
            - DB_NAME=peakplanner
            - DB_ROOT_PASSWORD=12345678

     
